config/routes.rb
Pastebin::Application.routes.draw do

  resources :pages

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

match '/pasteit', to: 'pages#new'

end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  title      :string(255)
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Page < ActiveRecord::Base
  attr_accessible :content, :name, :title

  
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true

  before_create :create_url_hash
  before_create :create_remember_token


  	private
  		def create_url_hash
  			o =  [('a'..'z'),('A'..'Z')].map{|i| i.to_a}.flatten
 			string  =  (0...16).map{ o[rand(o.length)] }.join
 			assign_url_hash(string)
 		end

 		def assign_url_hash(string)

 			if Page.find_by_url_hash(string)
 			create_url_hash 
 			else
 			self.url_hash = string 
 			end
 		end


 		def create_remember_token

 			self.remember_token = SecureRandom.urlsafe_base64
		end
 	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include PagesHelper
  before_filter :site_navigation

  def site_navigation
  	@navigation_links = { Home: root_path, About: about_path, Help: help_path }
  end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def create
  	@page = Page.new(params[:page])
	  
    if @page.save
      cookies_handler    
      redirect_to page_path(@page.url_hash)
      flash[:success] = "New paste Created!"
    else
      render 'new'  
	  end
  end

  def index
    @page = Page.find_all_by_remember_token(cookies[:remember_token]).reverse
    @page_public = Page.last(25).reverse
    @count = Page.find_all_by_remember_token(cookies[:remember_token]).length


  end

  def show
    @current_page_url = "#{request.protocol}#{request.host_with_port}#{request.fullpath}"
  	@page = Page.find_by_url_hash(params[:id])
    @count = Page.find_all_by_remember_token(cookies[:remember_token]).length
  end

  def edit
    @page = Page.find_by_url_hash(params[:id])
    if cookies[:remember_token] != @page.remember_token
       flash[:error] = "This paste doesn't belong to you ;)"
       redirect_to page_path(@page.url_hash)
    end
    
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
       cookies[:remember_token] = { value: @page.remember_token, expires: 1.hour.from_now.utc }
      redirect_to page_path(@page.url_hash)
      flash[:success] = "Your paste has been updated!"
    else
      render 'edit'
    end
  end


  def new
  	@page = Page.new
  end

  def destroy
    @page = Page.find_by_url_hash(params[:id])
    if cookies[:remember_token] == @page.remember_token
      @page.destroy
      flash[:success] = "Page Deleted!"
      redirect_to pages_path
    else
      flash[:error] = "This Page doesn't belong to you! :P"
      redirect_to page_path(@page.url_hash)
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

		def full_title(page_title)
		base_title = "Sample RoR Pastebin"
		if page_title.blank?
			base_title
		else 
		 	"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
def user_name(string)
	if string.blank?
		"Anonymous"
	else
		"#{string}"
	end
end

def current_pages
  	@_current_pages ||= session[:current_page] && Page.find_by_url_hash(session[:current_page]) 
  end


def cookies_handler
	if cookies[:remember_token].nil?

    cookies[:remember_token] = { value: @page.remember_token, expires: 1.hour.from_now.utc }
    
    else
       @page.remember_token= cookies[:remember_token]
       cookies[:remember_token] = { value: @page.remember_token, expires: 1.hour.from_now.utc }
       @page.save
    end
end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
  <footer id="footer">
    <div class="footnote-left">
      [pastebin(master)]$ <span class="dark-text">Developed by Manjunath Mt...</span>
    </div>
    <div class="footnote-right">
      Proudly Powered by <%= link_to 'Rails', 'http://rubyonrails.org/', class: 'dark-text' %> </div> 

  </footer>

app/views/layouts/_header.html.erb
  <header> 
  	<div class="navbar navbar-fixed-top">  
      <div class="navbar-inner">  
        <div class="container-fluid">  
           
          <%= link_to "", root_path, class: "icon-puzzle-piece icon-2x img-logo" %>
          <%=  link_to "Pastebin", root_path, id: 'logo'  %>

      	  <ul class="nav pull-right">
  				  <% @navigation_links.each do |key, value| %>
  				    <li> <%= link_to key, value %></li>
  				  <% end %> 
  			  </ul>
  		 
  		  </div>
  	  </div>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<%= render 'layouts/shim' %>

</head>
<body>
 <%= render 'layouts/header' %>
  	<div class="container">
      <div> 
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"> <%= value %> </div>
        <% end %>
      </div>
      <div class="hero-unit contenter">
		    <%= yield %>
        	
	   </div>

        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>	
</body>
</html>

app/views/pages/edit.html.erb
<% provide(:title, "Edit #{@page.title}!") %>
<h1><%= "Edit #{@page.title}!" %> </h1>
<h2> Your session would expire in 1 hour. </h2>

<div class="row">
  <div class="span8 offset0 ">
  	<%= form_for(@page) do |f| %>

      <%= render 'shared/errors' %>

      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :content %>
      <%= f.text_area :content, class: "text-field" %>

  	  <%= f.label :name, "Name(Optional)" %>
  	  <%= f.text_field :name  %>

  	  <%= f.submit "Update", class: 'btn btn-primary btn-large center' %>

  	<% end %>
 </div>
</div>

app/views/pages/index.html.erb
<% provide(:title, "Recent Pastes") %>
<h1>Recent Pastes</h1>
<br>

<div class="row">

	<div class="span6 offset0">
		<table class="table table-striped tabledividerright ">
			<thead>  
          	<h2> Your recent Pastes </h2>
            </thead>
            <tbody>  
            	
          <tr><% if @count!=0 %> 
          	<% @page.each do |page| %> 
            <td class="dark-text"><%= page.title %></td>  
            <td><%= link_to "View", page_path(page.url_hash), class: "light-text" %></td>  
            <td><%= link_to "Edit", edit_page_path(page.url_hash), class: "light-text" %></td>  
            <td><%= link_to "Delete", page_path(page.url_hash),  method: :delete,
                                  data: { confirm: "You sure?" } , class: "light-text" %></td>  
               
          </tr> 
          <% end %>
          <% else %>
          <p class="light-text"> You don't have any pastes yet! </p>
          <% end %>
        </table>
	</div>
	
   <div class="span1"></div>
   <div class="span4">
	<table class="table table-striped tabledividerleft">
			<thead>  
          	<h2> All Pastes </h2>
            </thead>
            <tbody>  
          <tr> <% @page_public.each do |page|  %> 
          	<td class="dark-text"><%= page.title %></td>
          	<td><%= link_to "View", page_path(page.url_hash), class: "light-text" %></td>  
            
               
          </tr> 
          <% end %>
      </tbody>
	</table>
   </div>
   </div>
   <div class="row">	
   
<%= link_to "Paste Another", pasteit_path, class: "dark-text text-align" %> <i class="icon-chevron-sign-right icon-2x"></i> 
</div>

app/views/pages/new.html.erb
<% provide(:title, "Paste it!") %>
<h1>Paste it!</h1>
<h2> It's really that easy! </h2>

<div class="row">
  <div class="span8 offset0 ">
  	<%= form_for(@page) do |f| %>
      <%= render 'shared/errors' %>

      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :content %>
      <%= f.text_area :content, class: "text-field" %>

  	  <%= f.label :name, "Name(Optional)" %>
  	  <%= f.text_field :name  %>

  	  <%= f.submit "Submit", class: 'btn btn-secondary btn-large center' %>

  	<% end %>
 </div>
</div>

app/views/pages/show.html.erb
<% provide(:title, @page.title) %>


<h1><%= @page.title %></h1>
<div class="show-text">
<div class="perm-url">  Permanent URI: <%= @current_page_url %></div>
<div class="show-content"><%= simple_format(@page.content) %></div>
</div>
<div class="step-down">
<p class="step-down-left"> Posted by <span class="dark-text"> <%= user_name(@page.name) %> </span></p>
<div class="step-down-right"> 
<ul>
<li> <%= link_to "Paste Another", pasteit_path, class: "dark-text text-align" %> <i class="icon-chevron-sign-right icon-2x"></i> </li>
<li> <%= link_to "Edit", edit_page_path(@page.url_hash), class: "dark-text text-align" %> <i class="icon-edit-sign icon-2x"></i>  </li>
<li> <%= link_to "Delete", page_path(@page.url_hash),  method: :delete,
                                  data: { confirm: "You sure?" }, class: "dark-text text-align" %> <i class="icon-remove icon-2x"></i>  </li>
 <li><% if @count>0 %> <%= link_to "My pastes", pages_path, class: "dark-text text-align" %> <i class="icon-reorder icon-2x"></i> <% end %></li></ul>

</div>
</div>

app/views/shared/_errors.html.erb
<% if @page.errors.any? %>
	<div id="error-explanation">
		<div class="alert alert-error">
		This paste contains <%= pluralize(@page.errors.count, "error") %>.
	</div>
	<ul>
  		<% @page.errors.full_messages.each do |error| %>
		<li> <%= error %> </li>
	<% end %>
	</ul>
		
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1> About Us </h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help Page</h1>

app/views/static_pages/home.html.erb
<% provide(:title, " ") %>
<h1> Sample RoR Pastebin App </h1>
<h2> This is a <%= link_to "bootstrap", 'http://twitter.github.io/bootstrap/', class: 'light-text' %> powered <%= link_to "Rails app", 'http://rubyonrails.org/', class: 'dark-text' %> developed by Manjunath Mt</h2>
<div class="center">
	<%= link_to "Paste it!", pasteit_path, class: "btn btn-primary btn-large" %>
</div>